---
title: "615_Assignment2"
author: "Lauren Marie"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load('dplyr', 'ggplot2', 'tidyr', 'knitr', 'stringr', 'tibble')
```


```{r}
aid<- aid_given_2007_us

names(aid)<- str_replace(names(aid), "X", "")

aidgiven<- rename(.data=aid, Country=ï..country)

aidgiven<- aidgiven %>% pivot_longer(!Country, names_to ="Year", values_to ="count")

health<- health_aid_given_percent_of_aid
names(health)<- str_replace(names(health), "X", "")
healthaid<- rename(.data=health, Country=ï..country)
healthaid<- healthaid %>% pivot_longer(!Country, names_to="Year", values_to="count")

compareaid<- left_join(aidgiven, healthaid, by=c("Year", "Country"))

compareaid<- rename(.data=compareaid, Aid=count.x, Health_Percent=count.y)
compareaid%>%kable()
is_tibble(compareaid)

plot<- function(a,b){
  {
    Country<-a
    data2<- filter(b, Country==a, Year>1996)
    c<-ggplot(data=data2)+geom_col(aes(x=Year, y=Aid, fill=Health_Percent))+ggtitle(Country)
    print(c)
  }
}
```
The data sets we are looking at are aid given from 1966 to 2006 as well as the percentage of that aid that went to health aid.
I chose to focus on the years 1997-2006 in two of the countries that give the most amount of aid, the United States and Japan. 
```{r}
plot("United States", compareaid)
```


```{r}
plot("Japan", compareaid)
```







